apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: cart
  name: cart
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: cart
  strategy: {}
  template:
    metadata:
      labels:
        io.kompose.network/e-commercenew20-my-network: "true"
        io.kompose.service: cart
    spec:
      containers:
        - env:
            - name: MYSQL_DATABASE
              value: ecommerce_fyp_cart
            - name: MYSQL_HOST
              value: host.docker.internal
            - name: MYSQL_PASSWORD
              value: "12345"
            - name: MYSQL_PORT
              value: "3306"
            - name: MYSQL_USER
              value: root
            - name: PRODUCT_API_URL
              value: product:8001
          image: richardgsc/cart:v1.0
          name: cart
          ports:
            - containerPort: 8005
              #hostPort: 8005
              protocol: TCP
          resources:
            limits:
              cpu: 300m
            requests:
              cpu: 150m
      restartPolicy: Always
status: {}
