apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: user
  name: user
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: user
  strategy: {}
  template:
    metadata:
      labels:
        io.kompose.network/e-commercenew20-my-network: "true"
        io.kompose.service: user
    spec:
      containers:
        - env:
            - name: MYSQL_DATABASE
              value: ecommerce_fyp_new
            - name: MYSQL_HOST
              value: host.docker.internal
            - name: MYSQL_PASSWORD
              value: "12345"
            - name: MYSQL_PORT
              value: "3306"
            - name: MYSQL_USER
              value: root
          image: richardgsc/user:v1.0
          name: user
          ports:
            - containerPort: 8080
              #hostPort: 8080
              protocol: TCP
          resources:
            limits:
              cpu: 300m
            requests:
              cpu: 150m
      restartPolicy: Always
status: {}
